name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.16.5

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Terraform format check
        run: terraform fmt -check -recursive

      - name: Initialize TFLint
        run: tflint --init

      - name: TFLint bootstrap
        working-directory: bootstrap
        run: tflint

      - name: TFLint infrastructure
        working-directory: infrastructure
        run: tflint

      - name: Initialize bootstrap
        working-directory: bootstrap
        run: terraform init -backend=false

      - name: Validate bootstrap
        working-directory: bootstrap
        run: terraform validate

      - name: Initialize infrastructure
        working-directory: infrastructure
        run: terraform init -backend=false

      - name: Validate infrastructure
        working-directory: infrastructure
        run: terraform validate
